# Generated by Django 3.1.7 on 2021-04-11 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('shrimps', '0001_initial'), ('shrimps', '0002_auto_20210411_1429')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(verbose_name='mm')),
                ('weight', models.IntegerField(verbose_name='g')),
                ('color', models.CharField(choices=[('pink', 'pink'), ('white', 'white'), ('green', 'green'), ('red', 'red'), ('purple', 'purple'), ('rainbow', 'rainbow')], max_length=32)),
                ('is_farmed', models.BooleanField(default=True)),
            ],
        ),
    ]
