# Generated by Django 3.1.7 on 2021-04-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('birth_date', models.DateTimeField(verbose_name='is born')),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('color', models.CharField(choices=[('PI', 'Pink'), ('WH', 'White'), ('GR', 'Green'), ('RE', 'Red'), ('PU', 'Purple'), ('RA', 'Rainbow')], max_length=2)),
                ('is_farmed', models.BooleanField(default=True)),
            ],
        ),
    ]
