# Generated by Django 3.1.7 on 2021-04-05 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('birth_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.IntegerField(verbose_name='size (cm)')),
                ('weight', models.IntegerField(verbose_name='weight (g)')),
                ('color', models.CharField(choices=[('PINK', 'pink'), ('WHITE', 'white'), ('GREEN', 'green'), ('RED', 'red'), ('PURPLE', 'purple'), ('RAINBOW', 'rainbow')], max_length=32)),
                ('is_farmed', models.BooleanField(default=True)),
            ],
        ),
    ]
