# Generated by Django 3.1.7 on 2021-04-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shrimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=126)),
                ('birth_date', models.DateTimeField(verbose_name='birth date')),
                ('size', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('color', models.CharField(choices=[('pink', 'pink'), ('white', 'white'), ('green', 'green'), ('red', 'red'), ('purple', 'purple'), ('rainbow', 'rainbow')], max_length=32)),
                ('is_farmed', models.BooleanField()),
            ],
        ),
    ]
