# Generated by Django 3.1.7 on 2021-04-09 20:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shrimps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimp',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 20, 19, 47, 171269, tzinfo=utc), verbose_name='is born'),
        ),
    ]
