# Generated by Django 3.1.7 on 2021-04-09 20:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shrimps', '0002_auto_20210409_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimp',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 9, 20, 21, 0, 743031, tzinfo=utc), verbose_name='is born'),
        ),
    ]
