# Generated by Django 3.1.7 on 2021-04-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrimps', '0003_auto_20210409_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimp',
            name='birth_date',
            field=models.DateTimeField(default='2021-04-09 11:30:47'),
        ),
    ]
