# Generated by Django 3.1.7 on 2021-04-09 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shrimps', '0004_auto_20210409_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shrimp',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='is born'),
        ),
    ]
